### ISSUE TITLE
URl naar AHN data

### ISSUE THREAD

**Issue by BasDeBas** [Jellest/rAHNextract#5]
De url https://geodata.nationaalgeoregister.nl/ahn3/wcs?
Lijkt niet meer te bestaan. 
Kennelijk moeten wij nu naar https://service.pdok.nl/rws/ahn3/wmts/v1_0?request=getcapabilities&service=wmts

**Comment by Jellest** [comment]
Ik ben bezig om de URLS te vervangen naar de nieuwe

**Comment by Jellest** [comment]
Package is aangepast en kijkt nu naar werkende URLs van PDOK.

**Comment by BasDeBas** [comment]
Fijn, bedankt

Van: Jelle Stuurman ***@***.***>
Verzonden: woensdag 17 april 2024 17:32
Aan: Jellest/rAHNextract ***@***.***>
CC: Delft, Bas van ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Jellest/rAHNextract] URl naar AHN data (Issue #5)


Closed #5<https://github.com/Jellest/rAHNextract/issues/5> as completed.

-
